-- Create the user_data table for pet owners and their pets
create table user_data (
  id bigint generated by default as identity primary key,
  owner_name text not null,
  pet_name text not null,
  pet_type text not null,
  age integer not null,
  special_needs text,
  status text not null default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table user_data enable row level security;

-- Create policy to allow authenticated users to read their own records
create policy "Users can read their own records"
on user_data for select
using (auth.uid() = owner_id);

-- Create policy to allow authenticated users to insert their own records
create policy "Users can insert their own records"
on user_data for insert
with check (true);

-- Add owner_id column and foreign key constraint
alter table user_data add column owner_id uuid references auth.users(id);